export const SETTINGS_TOOLTIPS = {
  reverseInitiative: 'Sorts initiative from low to high instead of high to low.',
  popcornInitiative: 'Lets players choose the next acting unit manually instead of following initiative order.',
  initiativeDie: 'Sets the die used when rolling initiative from the list (for example D20).',
  initiativeModifierAttr: 'Selects the numeric attribute used in initiative modifier math.',
  initiativeModifierMath: 'Math formula applied to the selected attribute. Use @STAT as the attribute value.',
  showCardColumn: 'Shows a quick-access column to open each unit\'s card/stat block.',
  showPlayerView: 'Allows Players to access the Initiative List view. If disabled, Players are routed away from the list.',
  showNonPartyUnits: 'If disabled, non-party unit stats are obscured for Players while keeping turn order visibility.',
  showHpNumbersOnList: 'If disabled, Players do not see exact HP/Max HP values in the Initiative List for non-owned units.',
  ownerOnlyEdit: 'Restricts editing controls to GMs and token owners.',
  showAdjustHpContextMenu: 'Shows or hides context menu options used to modify HP quickly.',
  showViewUnitContextMenuForPlayers: 'Shows or hides the View Unit right-click context menu option for Players while keeping it available for GMs.',
  showHpBarsOnTokens: 'Displays graphical HP bars on tokens in the scene.',
  hpOrientation: 'Sets where HP bars or HP numbers are anchored relative to tokens.',
  showHpNumbersOnTokens: 'Displays current/max HP numbers directly on tokens.',
  showDeathEffect: 'Shows a death visual effect when configured death conditions are met.',
  showNamesOnTokens: 'Toggles token name text visibility in scene.',
  showTurnEffect: 'Shows the active turn visual indicator in scene.',
  useDescriptiveNames: 'Appends descriptive suffixes to duplicate unit names for easier identification.',
  enableRumble: 'Enables Rumble integration for dice rolls.',
  enableBones: 'Enables Bones integration for dice rolls.',
  enableDicePlus: 'Enables Dice+ integration for dice rolls.',
  enableTextBasedRolls: 'Enables built-in text-based dice rolling handled directly by Forge.',
  enableObrNotification: 'Enables in-app Owlbear notifications for supported roll and system events.',
  showResultsToAll: 'When enabled, notifications are shown to all players instead of only the local user.',
  enableDiscordLogging: 'Sends roll or event logs to a configured Discord webhook.',
  discordUrl: 'Discord webhook endpoint used when Discord logging is enabled.',
  enableConsoleLog: 'Turns verbose Forge logging on or off in the browser console.',
} as const;
